name: Continuous Integration

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    name: Gradle Build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Zulu JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"
      - name: Build
        run: ./gradlew clean build
        env:
          SDK_INTEGRATION_TESTS_SERVER_API_URL: ${{ secrets.SDK_INTEGRATION_TESTS_SERVER_API_URL }}
          SDK_INTEGRATION_TESTS_SERVER_KEY_ID: ${{ secrets.SDK_INTEGRATION_TESTS_SERVER_KEY_ID }}
          SDK_INTEGRATION_TESTS_SERVER_KEY_SECRET: ${{ secrets.SDK_INTEGRATION_TESTS_SERVER_KEY_SECRET }}
