name: Integration Tests

on: workflow_dispatch

jobs:
  integration-test:
    runs-on: ubuntu-latest-8-cores
    name: Integration Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Zulu JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"
      - name: Build and run tests
        run: |
          hostname
          echo "host is $HOSTNAME"
          ./gradlew clean test -x check
        env:
          SDK_INTEGRATION_TESTS_SERVER_API_URL: ${{ secrets.SDK_INTEGRATION_TESTS_SERVER_API_URL }}
          SDK_INTEGRATION_TESTS_SERVER_KEY_ID: ${{ secrets.SDK_INTEGRATION_TESTS_SERVER_KEY_ID }}
          SDK_INTEGRATION_TESTS_SERVER_KEY_SECRET: ${{ secrets.SDK_INTEGRATION_TESTS_SERVER_KEY_SECRET }}
          USER1_APPLICATION_ID: ${{ secrets.USER1_APPLICATION_ID }}
          USER1_KEY_ID: ${{ secrets.USER1_KEY_ID }}
          USER1_SECRET: ${{ secrets.USER1_SECRET }}
          USER2_APPLICATION_ID: ${{ secrets.USER2_APPLICATION_ID }}
          USER2_KEY_ID: ${{ secrets.USER2_KEY_ID }}
          USER2_SECRET: ${{ secrets.USER2_SECRET }}
