# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish to Maven Central
on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Tag or branch to checkout'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Gradle Build and Publish
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref }}
      - name: Set up Zulu JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Publish
        run: ./gradlew publish -PmavenCentral -Pusername=${{ secrets.ORG_SONATYPE_USERNAME }} -Ppassword=${{ secrets.ORG_SONATYPE_PASSWORD }} -PsigningKey=${{ secrets.ORG_SIGNING_KEY }} -PsigningPassword=${{secrets.ORG_SIGNING_PASSWORD}}

